# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: "zig_study"  
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - "./.postgres-data/zig_study:/var/lib/postgres"
volumes:
  my-db: